// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/main.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HometownStation string `protobuf:"bytes,1,opt,name=hometownStation,proto3" json:"hometownStation,omitempty"`
	SkiResort       string `protobuf:"bytes,2,opt,name=skiResort,proto3" json:"skiResort,omitempty"`
	IsHoliday       bool   `protobuf:"varint,3,opt,name=isHoliday,proto3" json:"isHoliday,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_proto_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_proto_main_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetHometownStation() string {
	if x != nil {
		return x.HometownStation
	}
	return ""
}

func (x *Params) GetSkiResort() string {
	if x != nil {
		return x.SkiResort
	}
	return ""
}

func (x *Params) GetIsHoliday() bool {
	if x != nil {
		return x.IsHoliday
	}
	return false
}

type OneCandidateInLeg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineName         string `protobuf:"bytes,1,opt,name=lineName,proto3" json:"lineName,omitempty"`
	DepartureStation string `protobuf:"bytes,2,opt,name=departureStation,proto3" json:"departureStation,omitempty"`
	DepartureHour    uint32 `protobuf:"varint,3,opt,name=departureHour,proto3" json:"departureHour,omitempty"`
	DepartureMinute  uint32 `protobuf:"varint,4,opt,name=departureMinute,proto3" json:"departureMinute,omitempty"`
	ArrivalStation   string `protobuf:"bytes,5,opt,name=arrivalStation,proto3" json:"arrivalStation,omitempty"`
	ArrivalHour      uint32 `protobuf:"varint,6,opt,name=arrivalHour,proto3" json:"arrivalHour,omitempty"`
	ArrivalMinute    uint32 `protobuf:"varint,7,opt,name=arrivalMinute,proto3" json:"arrivalMinute,omitempty"`
}

func (x *OneCandidateInLeg) Reset() {
	*x = OneCandidateInLeg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_main_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneCandidateInLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneCandidateInLeg) ProtoMessage() {}

func (x *OneCandidateInLeg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_main_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneCandidateInLeg.ProtoReflect.Descriptor instead.
func (*OneCandidateInLeg) Descriptor() ([]byte, []int) {
	return file_proto_main_proto_rawDescGZIP(), []int{1}
}

func (x *OneCandidateInLeg) GetLineName() string {
	if x != nil {
		return x.LineName
	}
	return ""
}

func (x *OneCandidateInLeg) GetDepartureStation() string {
	if x != nil {
		return x.DepartureStation
	}
	return ""
}

func (x *OneCandidateInLeg) GetDepartureHour() uint32 {
	if x != nil {
		return x.DepartureHour
	}
	return 0
}

func (x *OneCandidateInLeg) GetDepartureMinute() uint32 {
	if x != nil {
		return x.DepartureMinute
	}
	return 0
}

func (x *OneCandidateInLeg) GetArrivalStation() string {
	if x != nil {
		return x.ArrivalStation
	}
	return ""
}

func (x *OneCandidateInLeg) GetArrivalHour() uint32 {
	if x != nil {
		return x.ArrivalHour
	}
	return 0
}

func (x *OneCandidateInLeg) GetArrivalMinute() uint32 {
	if x != nil {
		return x.ArrivalMinute
	}
	return 0
}

type CandidatesInOneLeg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidatesInOneLeg []*OneCandidateInLeg `protobuf:"bytes,1,rep,name=candidatesInOneLeg,proto3" json:"candidatesInOneLeg,omitempty"`
}

func (x *CandidatesInOneLeg) Reset() {
	*x = CandidatesInOneLeg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_main_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidatesInOneLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidatesInOneLeg) ProtoMessage() {}

func (x *CandidatesInOneLeg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_main_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidatesInOneLeg.ProtoReflect.Descriptor instead.
func (*CandidatesInOneLeg) Descriptor() ([]byte, []int) {
	return file_proto_main_proto_rawDescGZIP(), []int{2}
}

func (x *CandidatesInOneLeg) GetCandidatesInOneLeg() []*OneCandidateInLeg {
	if x != nil {
		return x.CandidatesInOneLeg
	}
	return nil
}

type AllLegsInOneWay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllLegsInOneWay []*CandidatesInOneLeg `protobuf:"bytes,1,rep,name=allLegsInOneWay,proto3" json:"allLegsInOneWay,omitempty"`
}

func (x *AllLegsInOneWay) Reset() {
	*x = AllLegsInOneWay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_main_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllLegsInOneWay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllLegsInOneWay) ProtoMessage() {}

func (x *AllLegsInOneWay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_main_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllLegsInOneWay.ProtoReflect.Descriptor instead.
func (*AllLegsInOneWay) Descriptor() ([]byte, []int) {
	return file_proto_main_proto_rawDescGZIP(), []int{3}
}

func (x *AllLegsInOneWay) GetAllLegsInOneWay() []*CandidatesInOneLeg {
	if x != nil {
		return x.AllLegsInOneWay
	}
	return nil
}

type Lines struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllLegsToSki *AllLegsInOneWay `protobuf:"bytes,1,opt,name=allLegsToSki,proto3" json:"allLegsToSki,omitempty"`
	AllLegsHome  *AllLegsInOneWay `protobuf:"bytes,2,opt,name=allLegsHome,proto3" json:"allLegsHome,omitempty"`
}

func (x *Lines) Reset() {
	*x = Lines{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_main_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lines) ProtoMessage() {}

func (x *Lines) ProtoReflect() protoreflect.Message {
	mi := &file_proto_main_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lines.ProtoReflect.Descriptor instead.
func (*Lines) Descriptor() ([]byte, []int) {
	return file_proto_main_proto_rawDescGZIP(), []int{4}
}

func (x *Lines) GetAllLegsToSki() *AllLegsInOneWay {
	if x != nil {
		return x.AllLegsToSki
	}
	return nil
}

func (x *Lines) GetAllLegsHome() *AllLegsInOneWay {
	if x != nil {
		return x.AllLegsHome
	}
	return nil
}

var File_proto_main_proto protoreflect.FileDescriptor

var file_proto_main_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x6e, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x68, 0x6f, 0x6d, 0x65, 0x74, 0x6f, 0x77, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x68, 0x6f, 0x6d,
	0x65, 0x74, 0x6f, 0x77, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x6b, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x6b, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73,
	0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x22, 0x9b, 0x02, 0x0a, 0x11, 0x4f, 0x6e, 0x65,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x4c, 0x65, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x64, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x75, 0x72, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x64,
	0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x28, 0x0a, 0x0f,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65,
	0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x72,
	0x12, 0x24, 0x0a, 0x0d, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x4d, 0x69, 0x6e, 0x75, 0x74,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c,
	0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x22, 0x5d, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x67, 0x12, 0x47, 0x0a, 0x12,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x4f, 0x6e, 0x65, 0x4c,
	0x65, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x4f, 0x6e, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x4c, 0x65,
	0x67, 0x52, 0x12, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x49, 0x6e, 0x4f,
	0x6e, 0x65, 0x4c, 0x65, 0x67, 0x22, 0x55, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x67, 0x73,
	0x49, 0x6e, 0x4f, 0x6e, 0x65, 0x57, 0x61, 0x79, 0x12, 0x42, 0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x4c,
	0x65, 0x67, 0x73, 0x49, 0x6e, 0x4f, 0x6e, 0x65, 0x57, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x49, 0x6e, 0x4f, 0x6e, 0x65, 0x4c, 0x65, 0x67, 0x52, 0x0f, 0x61, 0x6c, 0x6c,
	0x4c, 0x65, 0x67, 0x73, 0x49, 0x6e, 0x4f, 0x6e, 0x65, 0x57, 0x61, 0x79, 0x22, 0x7b, 0x0a, 0x05,
	0x4c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x4c, 0x65, 0x67, 0x73,
	0x54, 0x6f, 0x53, 0x6b, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x4c, 0x65, 0x67, 0x73, 0x49, 0x6e, 0x4f, 0x6e, 0x65, 0x57,
	0x61, 0x79, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x4c, 0x65, 0x67, 0x73, 0x54, 0x6f, 0x53, 0x6b, 0x69,
	0x12, 0x37, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x4c, 0x65, 0x67, 0x73, 0x48, 0x6f, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x6c, 0x6c,
	0x4c, 0x65, 0x67, 0x73, 0x49, 0x6e, 0x4f, 0x6e, 0x65, 0x57, 0x61, 0x79, 0x52, 0x0b, 0x61, 0x6c,
	0x6c, 0x4c, 0x65, 0x67, 0x73, 0x48, 0x6f, 0x6d, 0x65, 0x32, 0x33, 0x0a, 0x0a, 0x57, 0x61, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x6e, 0x65, 0x73, 0x12, 0x0c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x1a, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x42, 0x17,
	0x5a, 0x15, 0x77, 0x61, 0x79, 0x32, 0x73, 0x6b, 0x69, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_main_proto_rawDescOnce sync.Once
	file_proto_main_proto_rawDescData = file_proto_main_proto_rawDesc
)

func file_proto_main_proto_rawDescGZIP() []byte {
	file_proto_main_proto_rawDescOnce.Do(func() {
		file_proto_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_main_proto_rawDescData)
	})
	return file_proto_main_proto_rawDescData
}

var file_proto_main_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_main_proto_goTypes = []interface{}{
	(*Params)(nil),             // 0: main.Params
	(*OneCandidateInLeg)(nil),  // 1: main.OneCandidateInLeg
	(*CandidatesInOneLeg)(nil), // 2: main.CandidatesInOneLeg
	(*AllLegsInOneWay)(nil),    // 3: main.AllLegsInOneWay
	(*Lines)(nil),              // 4: main.Lines
}
var file_proto_main_proto_depIdxs = []int32{
	1, // 0: main.CandidatesInOneLeg.candidatesInOneLeg:type_name -> main.OneCandidateInLeg
	2, // 1: main.AllLegsInOneWay.allLegsInOneWay:type_name -> main.CandidatesInOneLeg
	3, // 2: main.Lines.allLegsToSki:type_name -> main.AllLegsInOneWay
	3, // 3: main.Lines.allLegsHome:type_name -> main.AllLegsInOneWay
	0, // 4: main.WayService.GetLines:input_type -> main.Params
	4, // 5: main.WayService.GetLines:output_type -> main.Lines
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_main_proto_init() }
func file_proto_main_proto_init() {
	if File_proto_main_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_main_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_main_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneCandidateInLeg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_main_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandidatesInOneLeg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_main_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllLegsInOneWay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_main_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lines); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_main_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_main_proto_goTypes,
		DependencyIndexes: file_proto_main_proto_depIdxs,
		MessageInfos:      file_proto_main_proto_msgTypes,
	}.Build()
	File_proto_main_proto = out.File
	file_proto_main_proto_rawDesc = nil
	file_proto_main_proto_goTypes = nil
	file_proto_main_proto_depIdxs = nil
}
